#!/usr/bin/env bash
# get-credentials.sh — extract the bootstrap server, CA cert and SCRAM
# password for the agent-mesh-controller user, formatted as a .env file
# that the local Next.js app reads at startup.
#
# Usage:
#   ./deploy/scripts/get-credentials.sh > .env.local
#
set -euo pipefail
KCTL="${KCTL:-oc}"
command -v "$KCTL" >/dev/null 2>&1 || KCTL=kubectl
NS="${NAMESPACE:-agent-mesh-sre}"
CLUSTER="${KAFKA_CLUSTER:-agent-mesh-kafka}"
USER="${KAFKA_USER:-agent-mesh-controller}"

bootstrap=$($KCTL get kafka "$CLUSTER" -n "$NS" \
  -o jsonpath='{.status.listeners[?(@.name=="external")].bootstrapServers}')
ca=$($KCTL get secret "${CLUSTER}-cluster-ca-cert" -n "$NS" \
  -o jsonpath='{.data.ca\.crt}' | base64 -d)
password=$($KCTL get secret "$USER" -n "$NS" \
  -o jsonpath='{.data.password}' | base64 -d)

cat <<EOF
# Generated by deploy/scripts/get-credentials.sh on $(date -Iseconds)
# Place at agent-mesh-sre/.env.local — Next.js will pick it up automatically.

KAFKA_MODE=real
KAFKA_NAMESPACE=$NS
KAFKA_CLUSTER=$CLUSTER
KAFKA_BOOTSTRAP=$bootstrap
KAFKA_USERNAME=$USER
KAFKA_PASSWORD=$password
KAFKA_CA_CERT_BASE64=$(echo -n "$ca" | base64 -w0)
EOF
